### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by cadmartin** [libfuse/pyfuse3#19]
While macOS lacks support for FUSE 3, there are mentions in the source about OS X compatibility, for example this commit https://github.com/libfuse/pyfuse3/commit/3686b57cef69e9d1412468a93e87f3854008ba50 and in setup.py.

Just curious as to whether the author was able to get this project work on OS X, and if so, what steps they took.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
