### ISSUE TITLE
WinFSP support?

### ISSUE THREAD

**Issue by dogtopus** [libfuse/pyfuse3#21]
https://github.com/billziss-gh/winfsp

Looks like they got a compatibility layer for both FUSE 2 and 3 so porting should be somewhat possible.

**Comment by Nikratio** [comment]
This is a great idea, thanks for taking the time to suggest it! Do you think you could work on this (or do you know someone who could)?

pyfuse3 is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. Suggestions for new features that are just submitted to the issue tracker are therefore unlikely to result in the feature being implemented - as great as the feature might be. 

So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by dogtopus** [comment]
Hm I do wish to help but I'm not sure I would get enough time working on it.

BTW feel free to close the issue for now and reopen it once I or somebody else got time or some working code.
