### ISSUE TITLE
travis-ci: test on python >= 3.5

### ISSUE THREAD

**Issue by ThomasWaldmann** [libfuse/pyfuse3#30]
setup.py tells that pyfuse 3 requires python >= 3.5, but travis-ci currently does not yet test all python versions >= 3.5.

**Comment by Nikratio** [comment]
That's because Python 3.5, 3.,6 and 3.7 are only shipping in Ubuntu versions older than focal, which do not contain libfuse3.

This could be fixed by installing libfuse3 from source (as we've done in the past), but this should only be done in the cases where it's not available as a package (to ensure that we test the packaged versions). Patches welcome :-).

**Comment by ThomasWaldmann** [comment]
Another option would be to use `pyenv` (slower, compiles python) or `deadsnakes` ppa (faster) to get these python version onto focal.

**Comment by Nikratio** [comment]
Tests are running with 3.8 and 3.9-dev now: https://travis-ci.com/github/libfuse/pyfuse3
