### ISSUE TITLE
sys.excepthook related warning?

### ISSUE THREAD

**Issue by ThomasWaldmann** [libfuse/pyfuse3#54]
https://github.com/borgbackup/borg/issues/6352 any idea what exactly is causing this?

in borgbackup, we do not use `sys.excepthook` and users are confused by the warning.

**Comment by Nikratio** [comment]
According to grep, there is no mention of `excepthook` anywhere in the pyfuse3 sources. So I don't think this is caused by pyfuse3. Perhaps just try to `print sys(excepthook)` at some point to see where it is defined?

**Comment by ThomasWaldmann** [comment]
Ah, ok, we'll try. Thanks!

**Comment by RenWal** [comment]
Apparently this is caused by libfuse3's dependency on trio (and borg then depends on libfuse3). There's [a comment in https://github.com/borgbackup/borg/issues/6352](https://github.com/borgbackup/borg/issues/6352#issuecomment-1072912485) that states that updating to trio 0.20.0 fixes the warning. Any possibility to bump trio in libfuse3?
